name: Publish Packages pipeline

## Warning: after successful publish the bot will delete the source branch

on:
  push:
    branches:
      - publish/*

jobs:
  publish-packages:
    runs-on: ubuntu-latest

    steps:
      # Use the main branch as source
      - uses: actions/checkout@v2
        name: Checkout
        with:
          ref: main
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: |
          npm ci --ignore-scripts
          npx lerna bootstrap --hoist --no-private
          npx lerna run build --no-private
        # env:
          # NODE_AUTH_TOKEN: ${{ secrets.READ_PACKAGES_PAT }}

      - name: Set Git Identity
        run: |
          git config --global user.name '🌈workflow-bot🤖'
          git config --global user.email 'workflow-bot@users.noreply.github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump packages
        run: |
          npx lerna version \
            --yes \
            --no-private \
            --conventional-commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NODE_AUTH_TOKEN: ${{ secrets.READ_PACKAGES_PAT }}

      - name: Publish packages
        run: |
          npx lerna publish from-package \
            --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NODE_AUTH_TOKEN: ${{ secrets.READ_PACKAGES_PAT }}

      - name: Delete release branch
        run: |
          echo current branch is ${{ github.ref }}
          git push origin --delete ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


